# Generated by Django 5.2.9 on 2025-12-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('bank_statement', 'Bank Statement'), ('purchase_order', 'Purchase Order'), ('expense_report', 'Expense Report'), ('check', 'Check'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk')], default='low_risk', max_length=20)),
                ('fraud_indicators', models.JSONField(blank=True, default=list)),
                ('component_scores', models.JSONField(blank=True, default=dict)),
                ('extracted_text', models.JSONField(blank=True, default=dict)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Analysis',
                'verbose_name_plural': 'Document Analyses',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
