# Generated by Django 5.2.9 on 2025-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_documentanalysis_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentanalysis',
            name='ai_analysis_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
