# Generated by Django 5.2.9 on 2025-12-31 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_documentanalysis_ai_analysis_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_evidence', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Item',
                'verbose_name_plural': 'Evidence Items',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('bank_statement', 'Bank Statement'), ('purchase_order', 'Purchase Order'), ('expense_report', 'Expense Report'), ('check', 'Check'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low_risk', 'Low Risk'), ('medium_risk', 'Medium Risk'), ('high_risk', 'High Risk'), ('non_financial', 'Non Financial')], default='low_risk', max_length=20)),
                ('fraud_indicators', models.JSONField(blank=True, default=list)),
                ('component_scores', models.JSONField(blank=True, default=dict)),
                ('extracted_text', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='detector.evidenceitem')),
            ],
            options={
                'verbose_name': 'Automated Scan',
                'verbose_name_plural': 'Automated Scans',
            },
        ),
        migrations.CreateModel(
            name='ForensicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Expert notes on the verdict')),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='detector.evidenceitem')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forensic Review',
                'verbose_name_plural': 'Forensic Reviews',
            },
        ),
        migrations.DeleteModel(
            name='DocumentAnalysis',
        ),
    ]
