# Generated by Django 5.2.9 on 2026-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='forensicreview',
            name='review_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores expert confidence, session time, and specialized flags'),
        ),
    ]
